#!/bin/bash
export WINEPREFIX="$HOME/.cemu/wine"
export WINEDLLOVERRIDES="mscoree=;mshtml=;cemuhook.dll=n,b"
lutrisver="7.2"
lutris="lutris-fshack-$lutrisver-x86_64"
lutrispath="$HOME/.local/share/lutris/runners/wine"
lutrissha1="7c8e9b8f7c8a5149860e4ec11691212da24c0365"
export PATH=$lutrispath/$lutris/bin:$PATH
export R600_DEBUG="nohyperz"

preparelutris() {
    lutrisver="$1"
    lutris="lutris-fshack-$lutrisver-x86_64"
    lutrispath="$HOME/.local/share/lutris/runners/wine"
    lutrissha1="$2"
    lutrislink="https://github.com/lutris/wine/releases/download/lutris-wine-$lutrisver/wine-$lutris.tar.xz"

    cd $HOME/Programs
    if [[ ! -e wine-$lutris.tar.xz || -e wine-$lutris.tar.xz.aria2 ]]; then
        aria2c $lutrislink
    fi

    lutrissha1L=$(shasum wine-$lutris.tar.xz | awk '{print $1}')
    if [[ $lutrissha1L != $lutrissha1 ]]; then
        echo "wine lutris $lutrisver verifying failed"
        echo "expected $lutrissha1, got $lutrissha1L"
        [[ ! -e wine-$lutris.tar.xz.aria2 ]] && rm -f wine-$lutris.tar.xz
        exit 1
    fi

    if [[ ! -d $lutrispath/$lutris ]]; then
        mkdir -p $lutrispath
        7z x wine-$lutris.tar.xz
        tar xvf wine-$lutris.tar -C $lutrispath
        rm -f wine-$lutris.tar
    fi
}

preparelutris "$lutrisver" "$lutrissha1"
cd $HOME/.cemu
wine Cemu.exe "$@"
